### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [Thomasbl/terraform#1]
Hi,<br><br>url : https://github.com/Thomasbl/terraform/blob/67b1d7adb5c8dc03b7fa42b3edf4f2326a80eae7/terraform-jenkins-298018-e3ca5de206a9.json <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by Thomasbl** [comment]
Hi,

It's for a school project, it's ok thx

Best regards
